name: my_chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "05001E"
  image: "assets/icons/logo.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
