name: my_chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.1.0
  modal_bottom_sheet: ^3.0.0-pre
  flutter_firebase_chat_core: ^1.6.7
  open_filex: ^4.3.4
  path_provider: ^2.1.2
  mime: ^1.0.5
  image_picker: ^1.0.7
  http: ^1.2.0
  flutter_chat_ui: ^1.6.10
  file_picker: ^6.1.1
  flutter_chat_types: ^3.6.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "05001E"
  image: "assets/icons/logo.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
